// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

listener http:Listener ep0 = new (9090);

// Payload validation is disabled here because several Pricefx request schemas mark large nested
// arrays as non-empty (`minLength: 1`); populating full business-realistic graphs (e.g. a Quote's
// line items) just to satisfy validation adds no value to these wire-format mock tests.
@http:ServiceConfig {validation: false}
service /pricefx/companypartition on ep0 {
    # User Login (V1)
    #
    # + return - OK
    resource function get login/extended() returns UserLoginResponse {
        return {
            response: {
                node: "companynode",
                status: 200,
                data: [
                    {typedId: "1.US", loginName: "jdoe", firstName: "Jane", lastName: "Doe", email: "jdoe@example.com", activated: true}
                ]
            }
        };
    }

    # Add a Customer
    #
    # + return - Returns customer record details
    resource function post add/C(@http:Payload AddCustomerRequest payload) returns CustomerResponseOk {
        return {
            body: {
                response: {
                    data: {typedId: "1001.C", name: "Acme Corp", customerId: "CUST-1001"},
                    status: 200
                }
            }
        };
    }

    # Add a Condition Record Set
    #
    # + return - OK
    resource function post add/CRCS(@http:Payload AddCRCSBody payload) returns ConditionRecordSetOperationEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "500.CRCS", uniqueName: "region-pricing", label: "Region Pricing Conditions", version: 1}
                    ]
                }
            }
        };
    }

    # Create a Manual Price List
    #
    # + return - Example response
    resource function post add/MPL(@http:Payload CreateManualPriceListRequest payload) returns ManualpricelistResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "2001.MPL", uniqueName: "q1-2026-promo", label: "Q1 2026 Promo Price List", status: "ACTIVE"}
                    ]
                }
            }
        };
    }

    # Add a Product
    #
    # + return - Returns full record details
    resource function post add/P(@http:Payload AddProductRequest payload) returns ProductResponseOk {
        return {
            body: {
                response: {
                    data: {typedId: "3001.P", sku: "SKU-3001", label: "Wireless Mouse"},
                    status: 200
                }
            }
        };
    }

    # Add a Seller
    #
    # + return - OK
    resource function post add/SL(@http:Payload AddSellerRequest payload) returns AddSellerEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "4001.SL", name: "John Carter", sellerId: "SL-4001"}
                    ]
                }
            }
        };
    }

    resource function post bdmanager\.list/[string typedId](@http:Payload BdmanagerListtypedIdBody payload) returns ListFilesEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 1,
                    totalRows: 1,
                    status: 200,
                    data: [
                        {typedId: "5001.BD", fileName: "invoice.pdf", length: 20480}
                    ]
                }
            }
        };
    }

    resource function post calculationgridmanager\.addgrid(@http:Payload AddCalculationGridRequest payload) returns AddCalculationGridResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "6001.CG", configuration: "Standard Discount Grid"}
                    ]
                }
            }
        };
    }

    resource function post calculationgridmanager\.calculate/[string id](@http:Payload CalculateCalculationGridRequest payload) returns CalculateCalculationGridResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {id: 7001, typedId: "7001.JST", targetObject: "6001.CG", trackerType: "CALCULATIONGRID"}
                    ]
                }
            }
        };
    }

    resource function post contractmanager\.fetch/[string uniqueName]() returns ContractModelResponseOk {
        return {
            body: {
                response: {
                    status: 200,
                    node: "companynode",
                    data: [
                        {typedId: "8001.CT", uniqueName: "acme-master-agreement", label: "Acme Master Agreement", workflowStatus: "APPROVED"}
                    ]
                }
            }
        };
    }

    resource function post contractmanager\.save(@http:Payload UpsertContractRequest payload) returns ContractModelResponseOk {
        return {
            body: {
                response: {
                    status: 200,
                    node: "companynode",
                    data: [
                        {typedId: "8002.CT", uniqueName: "globex-partner-agreement", label: "Globex Partner Agreement", workflowStatus: "DRAFT"}
                    ]
                }
            }
        };
    }

    resource function post customermanager\.fetchformulafilteredcustomers(@http:Payload ListCustomersRequest payload) returns CustomerResponseOk {
        return {
            body: {
                response: {
                    data: [
                        {typedId: "1001.C", name: "Acme Corp", customerId: "CUST-1001"},
                        {typedId: "1002.C", name: "Globex Inc", customerId: "CUST-1002"}
                    ],
                    startRow: 0,
                    endRow: 2,
                    totalRows: 2,
                    status: 200
                }
            }
        };
    }

    # Delete a Customer
    #
    # + return - OK
    resource function post delete/C(@http:Payload DeleteCustomerRequest payload) returns DeleteCustomerResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {
                            version: 1,
                            typedId: "1001.C",
                            customerId: "CUST-1001",
                            name: "Acme Corp",
                            nodeId: 1001,
                            createDate: "2026-01-15T10:00:00Z",
                            createdBy: 1,
                            lastUpdateDate: "2026-01-15T10:00:00Z",
                            lastUpdateBy: 1,
                            attribute1: "N/A",
                            attribute2: "N/A",
                            isParent: false
                        }
                    ]
                }
            }
        };
    }

    # Delete a Condition Records Set
    #
    # + return - OK
    resource function post delete/CRCS(@http:Payload DcrmanagerDeletemassopidBody payload) returns ConditionRecordSetOperationEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "500.CRCS", uniqueName: "region-pricing", label: "Region Pricing Conditions", version: 2}
                    ]
                }
            }
        };
    }

    # Delete a Product
    #
    # + return - OK
    resource function post delete/P(@http:Payload DeleteProductRequest payload) returns DeleteProductResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {
                            version: 1,
                            typedId: "3001.P",
                            sku: "SKU-3001",
                            label: "Wireless Mouse",
                            unitOfMeasure: "EA",
                            userGroupEdit: "Everyone",
                            userGroupViewDetails: "Everyone",
                            currency: "USD",
                            formulaName: "N/A",
                            image: false,
                            createDate: "2026-01-15T10:00:00Z",
                            createdBy: 1,
                            lastUpdateDate: "2026-01-15T10:00:00Z",
                            lastUpdateBy: 1,
                            attribute1: "N/A",
                            attribute2: "N/A"
                        }
                    ]
                }
            }
        };
    }

    # List Calculation Grids
    #
    # + return - OK
    resource function post fetch/CG(@http:Payload record {} payload) returns ListCalculationGridsResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 1,
                    totalRows: 1,
                    status: 200,
                    data: [
                        {typedId: "6001.CG", configuration: "Standard Discount Grid"}
                    ]
                }
            }
        };
    }

    # List Condition Record Sets
    #
    # + return - OK
    resource function post fetch/CRCS(@http:Payload record {} payload) returns ListConditionRecordSetsEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 1,
                    totalRows: 1,
                    status: 200,
                    data: [
                        {typedId: "500.CRCS", uniqueName: "region-pricing", label: "Region Pricing Conditions"}
                    ]
                }
            }
        };
    }

    # List Manual Price Lists
    #
    # + return - Example response
    resource function post fetch/MPL(@http:Payload ListManualPriceListsRequest payload) returns ManualpricelistResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "2001.MPL", uniqueName: "q1-2026-promo", label: "Q1 2026 Promo Price List", status: "ACTIVE"}
                    ]
                }
            }
        };
    }

    # List Price Lists
    #
    # + return - OK
    resource function post fetch/PL(@http:Payload ListPriceListsRequest payload) returns ListPriceListsResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 1,
                    totalRows: 1,
                    status: 200,
                    data: [
                        {typedId: "9001.PL", label: "Standard 2026 Price List", configuration: "Standard", approvalState: "APPROVED"}
                    ]
                }
            }
        };
    }

    # Get a Price List
    #
    # + id - The ID of the Price List you want to retrieve details for. The `id` is the `typedId` without the suffix. For example, the `id` attribute of the item with `typedId` = **2147484837.PL**  is **2147484837**
    # + return - OK
    resource function post fetch/PL/[string id]() returns GetPriceListResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "9001.PL", label: "Standard 2026 Price List", configuration: "Standard", approvalState: "APPROVED"}
                    ]
                }
            }
        };
    }

    resource function post pricelistmanager\.add(@http:Payload CreatePriceListRequest payload) returns CreatePriceListResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "9002.PL", configuration: "Standard", locale: "en_US"}
                    ]
                }
            }
        };
    }

    resource function post productmanager\.fetchformulafilteredproducts(@http:Payload ListProductsRequest payload) returns ProductResponseOk {
        return {
            body: {
                response: {
                    data: [
                        {typedId: "3001.P", sku: "SKU-3001", label: "Wireless Mouse"},
                        {typedId: "3002.P", sku: "SKU-3002", label: "Mechanical Keyboard"}
                    ],
                    startRow: 0,
                    endRow: 2,
                    totalRows: 2,
                    status: 200
                }
            }
        };
    }

    resource function post quotemanager\.fetch/[string typedID]() returns QuoteResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "10001.QU", uniqueName: "q-2026-001", label: "Acme Q1 Renewal Quote", workflowStatus: "DRAFT"}
                    ]
                }
            }
        };
    }

    resource function post quotemanager\.fetchlist(@http:Payload ListQuotesRequest payload) returns ListQuotesResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "10001.QU", quoteStatus: "OPEN", workflowStatus: "DRAFT", quoteType: "Standard"}
                    ]
                }
            }
        };
    }

    resource function post quotemanager\.save(@http:Payload UpsertQuoteRequest payload) returns QuoteResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "10002.QU", uniqueName: "q-2026-002", label: "Globex Renewal Quote", workflowStatus: "DRAFT"}
                    ]
                }
            }
        };
    }

    resource function post sellermanager\.fetchformulafilteredsellers(@http:Payload ListSellersRequest payload) returns ListSellersEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 2,
                    totalRows: 2,
                    status: 200,
                    data: [
                        {typedId: "4001.SL", name: "John Carter", sellerId: "SL-4001"},
                        {typedId: "4002.SL", name: "Maria Lopez", sellerId: "SL-4002"}
                    ]
                }
            }
        };
    }

    # Get an Authentication Token (API V2 only)
    #
    # + Pricefx\-Key - The Pricefx API key. Contact Pricefx Support to get your Pricefx-Key
    # + return - returns can be any of following types
    # http:Ok (Login was successful. The response contains the access token, token type and the refresh token)
    # http:BadRequest (The request was malformed.)
    # http:Unauthorized (Unauthorized - the login credentials were incorrect.
# )
    # http:Forbidden (Forbidden - The request did not contain a valid Pricefx-Key, the provided credentials in `body` were incorrect, the user was banned or not found or device registration required.)
    resource function post token(@http:Header {name: "Pricefx-Key"} string pricefxKey, @http:Payload GetAuthenticationTokenAPIv2Request payload) returns TokenResponseOk|GetAuthenticationTokenAPIv2400ResponseBadRequest|GetAuthenticationTokenAPIv2401ResponseUnauthorized|http:Forbidden {
        TokenResponseOk okResponse = {
            body: {
                access\-token: "mock-access-token-abc123",
                refresh\-token: "mock-refresh-token-xyz789",
                token\-type: "Bearer",
                expires\-in: 1800
            }
        };
        return okResponse;
    }

    # Update a Customer
    #
    # + return - Returns customer record details
    resource function post update/C(@http:Payload UpdateCustomerRequest payload) returns CustomerResponseOk {
        return {
            body: {
                response: {
                    data: {typedId: "1001.C", name: "Acme Corp Updated", customerId: "CUST-1001"},
                    status: 200
                }
            }
        };
    }

    # Update a Product
    #
    # + payload - Updates specified fields of the record. Only one record can be updated per request (unless batched).<p>
    # + return - Returns full record details
    resource function post update/P(@http:Payload UpdateProductRequest payload) returns ProductResponseOk {
        return {
            body: {
                response: {
                    data: {typedId: "3001.P", sku: "SKU-3001", label: "Wireless Mouse Pro"},
                    status: 200
                }
            }
        };
    }

    resource function post uploadmanager\.newuploadslot(string? ownerTypedId) returns CreateUploadSlotEnvelopeOk {
        return {
            body: {
                response: {
                    status: 200,
                    data: [
                        {id: "slot-001"}
                    ]
                }
            }
        };
    }
}
