// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;
import ballerinax/pricefx.oas;

listener http:Listener ep0 = new (9090);

// Counts calls to the `/accountmanager.fetchusers` mock below, which rejects its first call with a
// 401 so `testReauthenticatesAndRetriesOnUnauthorized` can verify the wrapper's retry behaviour.
isolated int listUsersCallCount = 0;

isolated function nextListUsersCall() returns int {
    lock {
        listUsersCallCount += 1;
        return listUsersCallCount;
    }
}

// Payload validation is disabled here because several Pricefx request schemas mark large nested
// arrays as non-empty (`minLength: 1`); populating full business-realistic graphs (e.g. a Quote's
// line items) just to satisfy validation adds no value to these wire-format mock tests.
@http:ServiceConfig {validation: false}
service /pricefx/companypartition on ep0 {
    # A mock OAuth 2.0 token endpoint. Ballerina's `http` module calls this itself (as part of its
    # built-in OAuth2 refresh token grant handling) to obtain an access token before the first
    # request that needs one, and again whenever it expires - this connector never calls it
    # directly. The response uses the standard OAuth2 field names (`access_token`, `token_type`,
    # `expires_in`), since that's what the `http` module's OAuth2 handling expects.
    #
    # + return - A standard OAuth2 token response
    resource function post oauth/token() returns json {
        return {
            access_token: "mock-oauth2-access-token",
            token_type: "Bearer",
            expires_in: 3600,
            refresh_token: "mock-oauth2-refresh-token"
        };
    }

    # Rejects its first call with a 401 and succeeds on every call after that, so tests can verify
    # that the wrapper re-authenticates and replays the request once instead of surfacing the 401.
    #
    # + return - `401 Unauthorized` on the first call, `200 OK` afterwards
    resource function post accountmanager\.fetchusers(@http:Payload oas:ListUsersRequest payload) returns oas:ListUsersResponse|http:Unauthorized {
        if nextListUsersCall() == 1 {
            return <http:Unauthorized>{body: {'error: "token expired"}};
        }
        return {
            response: {
                node: "companynode",
                status: 200,
                data: [{typedId: "1.US", loginName: "jdoe"}]
            }
        };
    }

    # Add a Customer
    #
    # + return - Returns customer record details
    resource function post add/C(@http:Payload oas:AddCustomerRequest payload) returns CustomerResponseOk {
        return {
            body: {
                response: {
                    data: {typedId: "1001.C", name: "Acme Corp", customerId: "CUST-1001"},
                    status: 200
                }
            }
        };
    }

    # Add a Condition Record Set
    #
    # + return - OK
    resource function post add/CRCS(@http:Payload oas:AddCRCSBody payload) returns ConditionRecordSetOperationEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "500.CRCS", uniqueName: "region-pricing", label: "Region Pricing Conditions", version: 1}
                    ]
                }
            }
        };
    }

    # Create a Manual Price List
    #
    # + return - Example response
    resource function post add/MPL(@http:Payload oas:CreateManualPriceListRequest payload) returns ManualpricelistResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "2001.MPL", uniqueName: "q1-2026-promo", label: "Q1 2026 Promo Price List", status: "ACTIVE"}
                    ]
                }
            }
        };
    }

    # Add a Product
    #
    # + return - Returns full record details
    resource function post add/P(@http:Payload oas:AddProductRequest payload) returns ProductResponseOk {
        return {
            body: {
                response: {
                    data: {typedId: "3001.P", sku: "SKU-3001", label: "Wireless Mouse", version: 1},
                    status: 200
                }
            }
        };
    }

    # Add a Seller
    #
    # + return - OK
    resource function post add/SL(@http:Payload oas:AddSellerRequest payload) returns AddSellerEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "4001.SL", name: "John Carter", sellerId: "SL-4001"}
                    ]
                }
            }
        };
    }

    resource function post bdmanager\.list/[string typedId](@http:Payload oas:BdmanagerListtypedIdBody payload) returns ListFilesEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 1,
                    totalRows: 1,
                    status: 200,
                    data: [
                        {typedId: "5001.BD", fileName: "invoice.pdf", length: 20480}
                    ]
                }
            }
        };
    }

    resource function post calculationgridmanager\.addgrid(@http:Payload oas:AddCalculationGridRequest payload) returns AddCalculationGridResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "6001.CG", configuration: "Standard Discount Grid"}
                    ]
                }
            }
        };
    }

    resource function post calculationgridmanager\.calculate/[string id](@http:Payload oas:CalculateCalculationGridRequest payload) returns CalculateCalculationGridResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {id: 7001, typedId: "7001.JST", targetObject: "6001.CG", trackerType: "CALCULATIONGRID"}
                    ]
                }
            }
        };
    }

    resource function post contractmanager\.fetch/[string uniqueName]() returns ContractModelResponseOk {
        return {
            body: {
                response: {
                    status: 200,
                    node: "companynode",
                    data: [
                        {typedId: "8001.CT", uniqueName: "acme-master-agreement", label: "Acme Master Agreement", workflowStatus: "APPROVED"}
                    ]
                }
            }
        };
    }

    resource function post contractmanager\.save(@http:Payload oas:UpsertContractRequest payload) returns ContractModelResponseOk {
        return {
            body: {
                response: {
                    status: 200,
                    node: "companynode",
                    data: [
                        {typedId: "8002.CT", uniqueName: "globex-partner-agreement", label: "Globex Partner Agreement", workflowStatus: "DRAFT"}
                    ]
                }
            }
        };
    }

    resource function post customermanager\.fetchformulafilteredcustomers(@http:Payload oas:ListCustomersRequest payload) returns CustomerResponseOk {
        return {
            body: {
                response: {
                    data: [
                        {typedId: "1001.C", name: "Acme Corp", customerId: "CUST-1001"},
                        {typedId: "1002.C", name: "Globex Inc", customerId: "CUST-1002"}
                    ],
                    startRow: 0,
                    endRow: 2,
                    totalRows: 2,
                    status: 200
                }
            }
        };
    }

    # Delete a Customer
    #
    # + return - OK
    resource function post delete/C(@http:Payload oas:DeleteCustomerRequest payload) returns DeleteCustomerResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {
                            version: 1,
                            typedId: "1001.C",
                            customerId: "CUST-1001",
                            name: "Acme Corp",
                            nodeId: 1001,
                            createDate: "2026-01-15T10:00:00Z",
                            createdBy: 1,
                            lastUpdateDate: "2026-01-15T10:00:00Z",
                            lastUpdateBy: 1,
                            attribute1: "N/A",
                            attribute2: "N/A",
                            isParent: false
                        }
                    ]
                }
            }
        };
    }

    # Delete a Condition Records Set
    #
    # + return - OK
    resource function post delete/CRCS(@http:Payload oas:DcrmanagerDeletemassopidBody payload) returns ConditionRecordSetOperationEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "500.CRCS", uniqueName: "region-pricing", label: "Region Pricing Conditions", version: 2}
                    ]
                }
            }
        };
    }

    # Delete a Product
    #
    # + return - OK
    resource function post delete/P(@http:Payload oas:DeleteProductRequest payload) returns DeleteProductResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {
                            version: 1,
                            typedId: "3001.P",
                            sku: "SKU-3001",
                            label: "Wireless Mouse",
                            unitOfMeasure: "EA",
                            userGroupEdit: "Everyone",
                            userGroupViewDetails: "Everyone",
                            currency: "USD",
                            formulaName: "N/A",
                            image: false,
                            createDate: "2026-01-15T10:00:00Z",
                            createdBy: 1,
                            lastUpdateDate: "2026-01-15T10:00:00Z",
                            lastUpdateBy: 1,
                            attribute1: "N/A",
                            attribute2: "N/A"
                        }
                    ]
                }
            }
        };
    }

    # List Calculation Grids
    #
    # + return - OK
    resource function post fetch/CG(@http:Payload record {} payload) returns ListCalculationGridsResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 1,
                    totalRows: 1,
                    status: 200,
                    data: [
                        {typedId: "6001.CG", configuration: "Standard Discount Grid"}
                    ]
                }
            }
        };
    }

    # List Condition Record Sets
    #
    # + return - OK
    resource function post fetch/CRCS(@http:Payload record {} payload) returns ListConditionRecordSetsEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 1,
                    totalRows: 1,
                    status: 200,
                    data: [
                        {typedId: "500.CRCS", uniqueName: "region-pricing", label: "Region Pricing Conditions"}
                    ]
                }
            }
        };
    }

    # List Manual Price Lists
    #
    # + return - Example response
    resource function post fetch/MPL(@http:Payload oas:ListManualPriceListsRequest payload) returns ManualpricelistResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "2001.MPL", uniqueName: "q1-2026-promo", label: "Q1 2026 Promo Price List", status: "ACTIVE"}
                    ]
                }
            }
        };
    }

    # List Price Lists
    #
    # + return - OK
    resource function post fetch/PL(@http:Payload oas:ListPriceListsRequest payload, @http:Header {name: "PriceFx-TFA"} string? priceFxTfa = (), @http:Header {name: "X-PriceFx-Csrf-Token"} string? priceFxCsrfToken = (), @http:Header string? authorization = (), @http:Header {name: "X-PriceFx-jwt"} string? xPriceFxJwt = ()) returns ListPriceListsResponseOk {
        // `node` echoes back the credentials this request arrived with, so the auth tests can
        // assert on exactly what reached the wire while still exercising a real business operation.
        return {
            body: {
                response: {
                    node: string `companynode|tfa=${priceFxTfa ?: ""}|csrf=${priceFxCsrfToken ?: ""}|auth=${authorization ?: ""}|jwt=${xPriceFxJwt ?: ""}`,
                    startRow: 0,
                    endRow: 1,
                    totalRows: 1,
                    status: 200,
                    data: [
                        {typedId: "9001.PL", label: "Standard 2026 Price List", configuration: "Standard", approvalState: "APPROVED"}
                    ]
                }
            }
        };
    }

    # Get a Price List
    #
    # + id - The ID of the Price List you want to retrieve details for. The `id` is the `typedId` without the suffix. For example, the `id` attribute of the item with `typedId` = **2147484837.PL**  is **2147484837**
    # + return - OK
    resource function post fetch/PL/[string id]() returns GetPriceListResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "9001.PL", label: "Standard 2026 Price List", configuration: "Standard", approvalState: "APPROVED"}
                    ]
                }
            }
        };
    }

    resource function post pricelistmanager\.add(@http:Payload oas:CreatePriceListRequest payload) returns CreatePriceListResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "9002.PL", configuration: "Standard", locale: "en_US"}
                    ]
                }
            }
        };
    }

    resource function post productmanager\.fetchformulafilteredproducts(@http:Payload oas:ListProductsRequest payload) returns ProductResponseOk {
        return {
            body: {
                response: {
                    data: [
                        {typedId: "3001.P", sku: "SKU-3001", label: "Wireless Mouse"},
                        {typedId: "3002.P", sku: "SKU-3002", label: "Mechanical Keyboard"}
                    ],
                    startRow: 0,
                    endRow: 2,
                    totalRows: 2,
                    status: 200
                }
            }
        };
    }

    resource function post quotemanager\.fetch/[string typedID]() returns QuoteResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "10001.QU", uniqueName: "q-2026-001", label: "Acme Q1 Renewal Quote", workflowStatus: "DRAFT"}
                    ]
                }
            }
        };
    }

    resource function post quotemanager\.fetchlist(@http:Payload oas:ListQuotesRequest payload) returns ListQuotesResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "10001.QU", quoteStatus: "OPEN", workflowStatus: "DRAFT", quoteType: "Standard"}
                    ]
                }
            }
        };
    }

    resource function post quotemanager\.save(@http:Payload oas:UpsertQuoteRequest payload) returns QuoteResponseOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    status: 200,
                    data: [
                        {typedId: "10002.QU", uniqueName: "q-2026-002", label: "Globex Renewal Quote", workflowStatus: "DRAFT"}
                    ]
                }
            }
        };
    }

    resource function post sellermanager\.fetchformulafilteredsellers(@http:Payload oas:ListSellersRequest payload) returns ListSellersEnvelopeOk {
        return {
            body: {
                response: {
                    node: "companynode",
                    startRow: 0,
                    endRow: 2,
                    totalRows: 2,
                    status: 200,
                    data: [
                        {typedId: "4001.SL", name: "John Carter", sellerId: "SL-4001"},
                        {typedId: "4002.SL", name: "Maria Lopez", sellerId: "SL-4002"}
                    ]
                }
            }
        };
    }

    # The session bootstrap the connector performs internally during `Client.init()` when
    # authenticating with username/password. Pricefx issues the session token as a cookie on the
    # first Basic authenticated call; the connector reads it from `Set-Cookie` and uses it for every
    # later request, so Basic auth's deliberate ~500ms penalty is paid once rather than per request.
    # `login` is not a public operation on the client, so nothing in the test suite calls this
    # directly - the connector does, before any other request.
    #
    # + return - `200 OK` carrying the session token as an `X-PriceFx-jwt` cookie
    resource function get login/extended() returns http:Ok {
        return {
            headers: {"Set-Cookie": "X-PriceFx-jwt=mock-session-jwt-abc123; Path=/; HttpOnly"},
            body: {response: {node: "companynode", status: 200}}
        };
    }

    # Update a Customer
    #
    # + return - Returns customer record details
    resource function post update/C(@http:Payload oas:UpdateCustomerRequest payload) returns CustomerResponseOk {
        return {
            body: {
                response: {
                    data: {typedId: "1001.C", name: "Acme Corp Updated", customerId: "CUST-1001"},
                    status: 200
                }
            }
        };
    }

    # Update a Product
    #
    # + payload - Updates specified fields of the record. Only one record can be updated per request (unless batched).<p>
    # + return - Returns full record details
    resource function post update/P(@http:Payload oas:UpdateProductRequest payload) returns ProductResponseOk {
        return {
            body: {
                response: {
                    data: {typedId: "3001.P", sku: "SKU-3001", label: "Wireless Mouse Pro"},
                    status: 200
                }
            }
        };
    }

    resource function post uploadmanager\.newuploadslot(string? ownerTypedId) returns CreateUploadSlotEnvelopeOk {
        return {
            body: {
                response: {
                    status: 200,
                    data: [
                        {id: "slot-001"}
                    ]
                }
            }
        };
    }
}

// A Pricefx deployment that does *not* hand back a session cookie on Basic auth. The connector must
// notice the token is absent and fall back to sending Basic credentials per request, rather than
// failing initialization - the bootstrap is a performance optimization, not a requirement.
@http:ServiceConfig {validation: false}
service /pricefx/nocookie on ep0 {
    # A login that authenticates but issues no `X-PriceFx-jwt` cookie.
    #
    # + return - `200 OK` with no session cookie
    resource function get login/extended() returns http:Ok {
        return {body: {response: {node: "companynode", status: 200}}};
    }

    # Echoes the `Authorization` header so the fallback test can confirm Basic auth is still used.
    #
    # + authorization - Echoed back, to show which credentials arrived
    # + return - OK
    resource function post fetch/PL(@http:Payload oas:ListPriceListsRequest payload, @http:Header string? authorization = ()) returns ListPriceListsResponseOk {
        return {
            body: {
                response: {
                    node: string `nocookie|auth=${authorization ?: ""}`,
                    status: 200,
                    data: [{typedId: "9001.PL", label: "Standard 2026 Price List"}]
                }
            }
        };
    }
}
