// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;
import ballerinax/pricefx.oas;

public type QuoteResponseOk record {|
    *http:Ok;
    oas:QuoteResponse body;
|};

public type CustomerResponseOk record {|
    *http:Ok;
    oas:CustomerResponse body;
|};

public type AddCalculationGridResponseOk record {|
    *http:Ok;
    oas:AddCalculationGridResponse body;
|};

public type ProductResponseOk record {|
    *http:Ok;
    oas:ProductResponse body;
|};

public type ListPriceListsResponseOk record {|
    *http:Ok;
    oas:ListPriceListsResponse body;
|};

public type ListFilesEnvelopeOk record {|
    *http:Ok;
    oas:ListFilesEnvelope body;
|};

public type CreateUploadSlotEnvelopeOk record {|
    *http:Ok;
    oas:CreateUploadSlotEnvelope body;
|};

public type ConditionRecordSetOperationEnvelopeOk record {|
    *http:Ok;
    oas:ConditionRecordSetOperationEnvelope body;
|};

public type GetPriceListResponseOk record {|
    *http:Ok;
    oas:GetPriceListResponse body;
|};

public type CreatePriceListResponseOk record {|
    *http:Ok;
    oas:CreatePriceListResponse body;
|};

public type ContractModelResponseOk record {|
    *http:Ok;
    oas:ContractModelResponse body;
|};

public type ListCalculationGridsResponseOk record {|
    *http:Ok;
    oas:ListCalculationGridsResponse body;
|};

public type ListSellersEnvelopeOk record {|
    *http:Ok;
    oas:ListSellersEnvelope body;
|};

public type DeleteCustomerResponseOk record {|
    *http:Ok;
    oas:DeleteCustomerResponse body;
|};

public type CalculateCalculationGridResponseOk record {|
    *http:Ok;
    oas:CalculateCalculationGridResponse body;
|};

public type ListConditionRecordSetsEnvelopeOk record {|
    *http:Ok;
    oas:ListConditionRecordSetsEnvelope body;
|};

public type ManualpricelistResponseOk record {|
    *http:Ok;
    oas:ManualPriceListResponse body;
|};

public type AddSellerEnvelopeOk record {|
    *http:Ok;
    oas:AddSellerEnvelope body;
|};

public type DeleteProductResponseOk record {|
    *http:Ok;
    oas:DeleteProductResponse body;
|};

public type ListQuotesResponseOk record {|
    *http:Ok;
    oas:ListQuotesResponse body;
|};
