// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

public type QuoteResponseOk record {|
    *http:Ok;
    quoteResponse body;
|};

public type CustomerResponseOk record {|
    *http:Ok;
    customerResponse body;
|};

public type AddCalculationGridResponseOk record {|
    *http:Ok;
    AddCalculationGridResponse body;
|};

public type ProductResponseOk record {|
    *http:Ok;
    productResponse body;
|};

public type GetAuthenticationTokenAPIv2401ResponseUnauthorized record {|
    *http:Unauthorized;
    GetAuthenticationTokenAPIv2401Response body;
|};

public type ListPriceListsResponseOk record {|
    *http:Ok;
    ListPriceListsResponse body;
|};

public type ListFilesEnvelopeOk record {|
    *http:Ok;
    ListFilesEnvelope body;
|};

public type CreateUploadSlotEnvelopeOk record {|
    *http:Ok;
    CreateUploadSlotEnvelope body;
|};

public type ConditionRecordSetOperationEnvelopeOk record {|
    *http:Ok;
    ConditionRecordSetOperationEnvelope body;
|};

public type GetPriceListResponseOk record {|
    *http:Ok;
    GetPriceListResponse body;
|};

public type GetAuthenticationTokenAPIv2400ResponseBadRequest record {|
    *http:BadRequest;
    GetAuthenticationTokenAPIv2400Response body;
|};

public type CreatePriceListResponseOk record {|
    *http:Ok;
    CreatePriceListResponse body;
|};

public type ContractModelResponseOk record {|
    *http:Ok;
    contractModelResponse body;
|};

public type ListCalculationGridsResponseOk record {|
    *http:Ok;
    ListCalculationGridsResponse body;
|};

public type ListSellersEnvelopeOk record {|
    *http:Ok;
    ListSellersEnvelope body;
|};

public type DeleteCustomerResponseOk record {|
    *http:Ok;
    DeleteCustomerResponse body;
|};

public type CalculateCalculationGridResponseOk record {|
    *http:Ok;
    CalculateCalculationGridResponse body;
|};

public type GetAuthenticationTokenAPIv2400Response record {
    @constraint:String {minLength: 1}
    string 'error;
};

public type ListConditionRecordSetsEnvelopeOk record {|
    *http:Ok;
    ListConditionRecordSetsEnvelope body;
|};

public type ManualpricelistResponseOk record {|
    *http:Ok;
    manualpricelistResponse body;
|};

public type GetAuthenticationTokenAPIv2401Response record {
    @constraint:String {minLength: 1}
    string 'error;
};

public type AddSellerEnvelopeOk record {|
    *http:Ok;
    AddSellerEnvelope body;
|};

public type TokenResponseOk record {|
    *http:Ok;
    tokenResponse body;
|};

public type DeleteProductResponseOk record {|
    *http:Ok;
    DeleteProductResponse body;
|};

public type ListQuotesResponseOk record {|
    *http:Ok;
    ListQuotesResponse body;
|};
